
// movies.forEach((a) => {
//     const $A = document.querySelector("#api");
    
//     const $divElement = document.createElement('div');
//     $divElement.className = 'card-container';
    
    
    
//     let card = `
//         <li class="movie-card" >
//         <img id="movie-img" alt="${a.img}" />
//         <div id="title1">${a.title}</div>
//         <p id="title2">${a.descirption}</p>
//         <p id="title3">평점</p> 
//         </li> 
//     `
    
//     $divElement.innerHTML = card;
    
//     $A.appendChild($divElement);

// })
